<a href="https://colab.research.google.com/github/Dielvic/KPMG-Analysis-Virtual-Stage/blob/main/Qualification_rapport.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [ ]:
'''xlsx = pd.ExcelFile('XX - Reporting Marketing Relationnel_V4.xlsx')

data = pd.read_excel(xlsx, 'Qualification')'''

"xlsx = pd.ExcelFile('XX - Reporting Marketing Relationnel_V4.xlsx')\n\ndata = pd.read_excel(xlsx, 'Qualification')"

In [ ]:
#data.head()

In [ ]:
df = pd.read_excel("Qualification.xlsx")

In [ ]:
df

         commentaire_     ID_ Exclusion_  ... type_ cible_  objet
0   Qualif incomplète  216989        NON  ...   NaN    NaN    NaN
1   Qualif incomplète  216990        NON  ...   NaN    NaN    NaN
2   Qualif incomplète  216992        NON  ...   NaN    NaN    NaN
3   Qualif incomplète  217000        NON  ...   NaN    NaN    NaN
4   Qualif incomplète  217001        NON  ...   NaN    NaN    NaN
5   Qualif incomplète  223910        NON  ...   NaN    NaN    NaN
6   Qualif incomplète  223958        NON  ...   NaN    NaN    NaN
7   Qualif incomplète  224682        NON  ...   NaN    NaN    NaN
8   Qualif incomplète  224859        NON  ...   NaN    NaN    NaN
9   Qualif incomplète  225186        NON  ...   NaN    NaN    NaN
10  Qualif incomplète  225501        NON  ...   NaN    NaN    NaN
11  Qualif incomplète  225820        NON  ...   NaN    NaN    NaN
12  Qualif incomplète  226482        NON  ...   NaN    NaN    NaN
13  Qualif incomplète  226943        NON  ...   NaN    NaN    NaN
14  Qualif incomplète  227420        NON  ...   NaN    NaN    NaN
15  Qualif incomplète  227421        NON  ...   NaN    NaN    NaN
16  Qualif incomplète  227430        NON  ...   NaN    NaN    NaN
17  Qualif incomplète  227628        NON  ...   NaN    NaN    NaN
18  Qualif incomplète  227933        NON  ...   NaN    NaN    NaN

[19 rows x 11 columns]

In [ ]:
from re import search

In [ ]:
#Remplissage de la colonne catégorie_
df["Catégorie_"]= "[NL] - AUTRES"
df.loc[df["Nom_e-mail"].str.contains("NL-SERVICES"), 'Catégorie_'] = '[NL] - SERVICE'
df.loc[(df["Nom_e-mail"].str.contains("OFFRE")|df["Nom_e-mail"].str.contains("OAAE") |df["Nom_e-mail"].str.contains("ETRADI")) , 'Catégorie_'] = "[NL] - OFFRE"
df.loc[df["Nom_e-mail"].str.contains("LABO"), 'Catégorie_'] = "[NL] - LABO"
df.loc[(df["Nom_e-mail"].str.contains("VERZENIOS")& df["Envois_"]>1), 'Catégorie_'] = "[NL] - LABO"
df.loc[df["Nom_e-mail"].str.contains("NL-ETRADI"), 'Catégorie_'] = "[NL] - OFFRE"
df.loc[df["Nom_e-mail"].str.contains("INFOFLASH") , 'Catégorie_'] = "[NL] - INFO"
df.loc[df["Nom_e-mail"].str.contains("IF"), 'Catégorie_'] = "[NL] - INFO"
df.loc[df["Nom_e-mail"].str.contains("EVENT"), 'Catégorie_'] = "[NL] - EVENT"

In [ ]:
df

         commentaire_     ID_ Exclusion_  ... type_ cible_  objet
0   Qualif incomplète  216989        NON  ...   NaN    NaN    NaN
1   Qualif incomplète  216990        NON  ...   NaN    NaN    NaN
2   Qualif incomplète  216992        NON  ...   NaN    NaN    NaN
3   Qualif incomplète  217000        NON  ...   NaN    NaN    NaN
4   Qualif incomplète  217001        NON  ...   NaN    NaN    NaN
5   Qualif incomplète  223910        NON  ...   NaN    NaN    NaN
6   Qualif incomplète  223958        NON  ...   NaN    NaN    NaN
7   Qualif incomplète  224682        NON  ...   NaN    NaN    NaN
8   Qualif incomplète  224859        NON  ...   NaN    NaN    NaN
9   Qualif incomplète  225186        NON  ...   NaN    NaN    NaN
10  Qualif incomplète  225501        NON  ...   NaN    NaN    NaN
11  Qualif incomplète  225820        NON  ...   NaN    NaN    NaN
12  Qualif incomplète  226482        NON  ...   NaN    NaN    NaN
13  Qualif incomplète  226943        NON  ...   NaN    NaN    NaN
14  Qualif incomplète  227420        NON  ...   NaN    NaN    NaN
15  Qualif incomplète  227421        NON  ...   NaN    NaN    NaN
16  Qualif incomplète  227430        NON  ...   NaN    NaN    NaN
17  Qualif incomplète  227628        NON  ...   NaN    NaN    NaN
18  Qualif incomplète  227933        NON  ...   NaN    NaN    NaN

[19 rows x 11 columns]

In [ ]:
Type = [["[AUTRES] - AUTRES", "[AUTRES] - HEBDOCP"],["[EVENT] - AUTRES", "[EVENT] - CARREFOURS DE L'INSTALLATION","[EVENT] - CONF BUXERAUD",
        "[EVENT] - INTERFIMO", "[EVENT] - PHARMAGORA", "[EVENT] - RENCONTRES DE L'OFFICINE"] , ["[INFO] - INFO LABO", "[INFO] - INFOFLASH", 
        "[INFO] - INFOPRO", "[INFO] - INFOREGLEMENTAIRE", "[INFO] - COVID"], ["[LABO] - CONTENU", "[LABO] - INFO INSTIT", "[LABO] - INFO PRODUIT",
        "[LABO] - OFFRE"], ["[LINK] - MON COMPTE OCP", "[OCPF] - VISIO FORMATION"], ["[OFFRES] - AUTRES OFFRES", "[OFFRES] - COVID", "[OFFRES] - EQUIPEMENT",
        "[OFFRES] - ETRADI", "[OFFRES] - GENERIQUES", "[OFFRES] - GRIPPE", "[OFFRES] - INCONTOURNABLES", "[OFFRES] - MARQUE CONSEIL",
        "[OFFRES] - OAAE", "[OFFRES] - OCPH", "[OFFRES] - OFFRE LINK", "[OFFRES] - OFFRES DU MOIS", "[OFFRES] - SOLUTIONS ACHATS",
        "[OFFRES] - TEMPS FORT PROMOTIONNEL"], ["[SERVICES] - AUTRES SERVICES", "[SERVICES] - DATAE", "[SERVICES] - FINANCEMENT", "[SERVICES] - FINANCEMENT EVENT",
        "[SERVICES] - FINANCEMENT EXTENSIO", "[SERVICES] - FINANCEMENT INITIO", "[SERVICES] - LINK", "[SERVICES] - MON OCPH", "[SERVICES] - OCPF",
        "[SERVICES] - OCPMFO", "[SERVICES] - PACK SERVICE", "[SERVICES] - PETITES ANNONCES", "[SERVICES] - SERVICE RELATION CLIENT",
        "[SERVICES] - SERVICES DE GESTION"]]

In [ ]:
df.loc[df["Catégorie_"].str.endswith("AUTRES") & df["Nom_e-mail"].str.contains("HEBDOCP") , 'type_'] = Type[0][1]
df.loc[df["Catégorie_"].str.endswith("AUTRES") & df["Nom_e-mail"].str.contains("AUTRES") , 'type_'] = Type[0][0]
df.loc[df["Catégorie_"].str.endswith("EVENT") & df["Nom_e-mail"].str.contains("AUTRES") , 'type_'] = Type[1][0]
df.loc[df["Catégorie_"].str.endswith("EVENT") & df["Nom_e-mail"].str.contains("CARREFOURS DE L'INSTALLATION") , 'type_'] = Type[1][1]
df.loc[df["Catégorie_"].str.endswith("EVENT") & df["Nom_e-mail"].str.contains("CONF BUXERAUD") , 'type_'] = Type[1][2]
df.loc[df["Catégorie_"].str.endswith("EVENT") & df["Nom_e-mail"].str.contains("INTERFIMO") , 'type_'] = Type[1][3]
df.loc[df["Catégorie_"].str.endswith("EVENT") & df["Nom_e-mail"].str.contains("PHARMAGORA") , 'type_'] = Type[1][4]
df.loc[df["Catégorie_"].str.endswith("EVENT") & df["Nom_e-mail"].str.contains("RENCONTRES DE L'OFFICINE") , 'type_'] = Type[1][5]
df.loc[df["Catégorie_"].str.endswith("INFO") & df["Nom_e-mail"].str.contains("INFO LABO") , 'type_'] = Type[2][0]
df.loc[df["Catégorie_"].str.endswith("INFO") & df["Nom_e-mail"].str.contains("INFOFLASH") , 'type_'] = Type[2][1]
df.loc[df["Catégorie_"].str.endswith("INFO") & df["Nom_e-mail"].str.contains("INFOPRO") , 'type_'] = Type[2][2]
df.loc[df["Catégorie_"].str.endswith("INFO") & df["Nom_e-mail"].str.contains("INFOREGLEMENTAIRE") , 'type_'] = Type[2][3]
df.loc[df["Catégorie_"].str.endswith("INFO") & df["Nom_e-mail"].str.contains("COVID") , 'type_'] = Type[2][4]
df.loc[df["Catégorie_"].str.endswith("LABO") & df["Nom_e-mail"].str.contains("CONTENU") , 'type_'] = Type[3][0]
df.loc[df["Catégorie_"].str.endswith("LABO") & df["Nom_e-mail"].str.contains("INFO INSTIT") , 'type_'] = Type[3][1]
df.loc[df["Catégorie_"].str.endswith("LABO") & (df["Nom_e-mail"].str.contains("INFO PRODUIT") | df["Nom_e-mail"].str.contains("LILLY") | df["Nom_e-mail"].str.contains("VERZENIOS")), 'type_'] = Type[3][2]
df.loc[df["Catégorie_"].str.endswith("LABO") & df["Nom_e-mail"].str.contains("OFFRE") , 'type_'] = Type[3][3]
df.loc[df["Catégorie_"].str.endswith("LINK") & df["Nom_e-mail"].str.contains("MON COMPTE OCP") , 'type_'] = Type[4][0]
df.loc[df["Catégorie_"].str.endswith("OCPF") & df["Nom_e-mail"].str.contains("VISIO FORMATION") , 'type_'] = Type[4][1]
df.loc[df["Catégorie_"].str.endswith("OFFRE") & df["Nom_e-mail"].str.contains("AUTRES OFFRES") , 'type_'] = Type[5][0]
df.loc[df["Catégorie_"].str.endswith("OFFRE") & df["Nom_e-mail"].str.contains("COVID") , 'type_'] = Type[5][1]
df.loc[df["Catégorie_"].str.endswith("OFFRE") & (df["Nom_e-mail"].str.contains("EQUIPEMENT")| df["Nom_e-mail"].str.contains("EQT")) , 'type_'] = Type[5][2]
df.loc[df["Catégorie_"].str.endswith("OFFRE") & df["Nom_e-mail"].str.contains("ETRADI") , 'type_'] = Type[5][3]
df.loc[df["Catégorie_"].str.endswith("OFFRE") & df["Nom_e-mail"].str.contains("GENERIQUES") , 'type_'] = Type[5][4]
df.loc[df["Catégorie_"].str.endswith("OFFRE") & (df["Nom_e-mail"].str.contains("GRIPPE") | df["Nom_e-mail"].str.contains("GEN")) , 'type_'] = Type[5][5]
df.loc[df["Catégorie_"].str.endswith("OFFRE") & df["Nom_e-mail"].str.contains("INCONTOURNABLES") , 'type_'] = Type[5][6]
df.loc[df["Catégorie_"].str.endswith("OFFRE") & (df["Nom_e-mail"].str.contains("MARQUE CONSEIL") | df["Nom_e-mail"].str.contains("MC")) , 'type_'] = Type[5][7]
df.loc[df["Catégorie_"].str.endswith("OFFRE") & df["Nom_e-mail"].str.contains("OAAE") , 'type_'] = Type[5][8]
df.loc[df["Catégorie_"].str.endswith("OFFRE") & df["Nom_e-mail"].str.contains("OCPH") , 'type_'] = Type[5][9]
df.loc[df["Catégorie_"].str.endswith("OFFRE") & df["Nom_e-mail"].str.contains("OFFRE LINK") , 'type_'] = Type[5][10]
df.loc[df["Catégorie_"].str.endswith("OFFRE") & (df["Nom_e-mail"].str.contains("ODM") | df["Nom_e-mail"].str.contains("LILLY")), 'type_'] = Type[5][11]
df.loc[df["Catégorie_"].str.endswith("OFFRE") & df["Nom_e-mail"].str.contains("SOLUTIONS ACHATS") , 'type_'] = Type[5][12]
df.loc[df["Catégorie_"].str.endswith("OFFRE") & df["Nom_e-mail"].str.contains("TEMPS FORT PROMOTIONNEL") , 'type_'] = Type[5][13]
df.loc[df["Catégorie_"].str.endswith("SERVICE") & df["Nom_e-mail"].str.contains("AUTRES SERVICES") , 'type_'] = Type[6][0]
df.loc[df["Catégorie_"].str.endswith("SERVICE") & df["Nom_e-mail"].str.contains("DATAE") , 'type_'] = Type[6][1]
df.loc[df["Catégorie_"].str.endswith("SERVICE") & df["Nom_e-mail"].str.contains("FINANCEMENT") , 'type_'] = Type[6][2]
df.loc[df["Catégorie_"].str.endswith("SERVICE") & df["Nom_e-mail"].str.contains("FINANCEMENT EVENT") , 'type_'] = Type[6][3]
df.loc[df["Catégorie_"].str.endswith("SERVICE") & df["Nom_e-mail"].str.contains("FINANCEMENT EXTENSIO") , 'type_'] = Type[6][4]
df.loc[df["Catégorie_"].str.endswith("SERVICE") & df["Nom_e-mail"].str.contains("INITIO") , 'type_'] = Type[6][5]
df.loc[df["Catégorie_"].str.endswith("SERVICE") & (df["Nom_e-mail"].str.contains("LINK") | df["Nom_e-mail"].str.contains("BONSUPGRADE")), 'type_'] = Type[6][6]
df.loc[df["Catégorie_"].str.endswith("SERVICE") & df["Nom_e-mail"].str.contains("OCPH") , 'type_'] = Type[6][3]
df.loc[df["Catégorie_"].str.endswith("SERVICE") & df["Nom_e-mail"].str.contains("OCPF") , 'type_'] = Type[6][2]
df.loc[df["Catégorie_"].str.endswith("SERVICE") & (df["Nom_e-mail"].str.contains("OCPMFO") | df["Nom_e-mail"].str.contains("MFO")) , 'type_'] = Type[6][9]
df.loc[df["Catégorie_"].str.endswith("SERVICE") & df["Nom_e-mail"].str.contains("PACK SERVICE") , 'type_'] = Type[6][10]
df.loc[df["Catégorie_"].str.endswith("SERVICE") & df["Nom_e-mail"].str.contains("PETITES ANNONCES") , 'type_'] = Type[6][11]
df.loc[df["Catégorie_"].str.endswith("SERVICE") & df["Nom_e-mail"].str.contains("SERVICE RELATION CLIENT") , 'type_'] = Type[6][12]
df.loc[df["Catégorie_"].str.endswith("SERVICE") & (df["Nom_e-mail"].str.contains("SERVICES DE GESTION") | df["Nom_e-mail"].str.contains("SG") 
                                                   | df["Nom_e-mail"].str.contains("SERVICESDEGESTION") | df["Nom_e-mail"].str.contains("DEMATVAGUE")) , 'type_'] = Type[6][13]

In [ ]:
df

         commentaire_     ID_  ... cible_ objet
0   Qualif incomplète  216989  ...    NaN   NaN
1   Qualif incomplète  216990  ...    NaN   NaN
2   Qualif incomplète  216992  ...    NaN   NaN
3   Qualif incomplète  217000  ...    NaN   NaN
4   Qualif incomplète  217001  ...    NaN   NaN
5   Qualif incomplète  223910  ...    NaN   NaN
6   Qualif incomplète  223958  ...    NaN   NaN
7   Qualif incomplète  224682  ...    NaN   NaN
8   Qualif incomplète  224859  ...    NaN   NaN
9   Qualif incomplète  225186  ...    NaN   NaN
10  Qualif incomplète  225501  ...    NaN   NaN
11  Qualif incomplète  225820  ...    NaN   NaN
12  Qualif incomplète  226482  ...    NaN   NaN
13  Qualif incomplète  226943  ...    NaN   NaN
14  Qualif incomplète  227420  ...    NaN   NaN
15  Qualif incomplète  227421  ...    NaN   NaN
16  Qualif incomplète  227430  ...    NaN   NaN
17  Qualif incomplète  227628  ...    NaN   NaN
18  Qualif incomplète  227933  ...    NaN   NaN

[19 rows x 11 columns]

In [ ]:
df["type_"].isna().sum()

3

In [ ]:
df[df["type_"].isna()]

         commentaire_     ID_ Exclusion_  ... type_ cible_  objet
5   Qualif incomplète  223910        NON  ...   NaN    NaN    NaN
8   Qualif incomplète  224859        NON  ...   NaN    NaN    NaN
11  Qualif incomplète  225820        NON  ...   NaN    NaN    NaN

[3 rows x 11 columns]

In [ ]:
df.to_excel('Qualif.xlsx')

In [ ]:
#!apt-get update

In [ ]:
#!pip install selenium

In [ ]:
#!apt install chromium-chromedriver

In [ ]:
#!pip install webdriver_manager

In [ ]:
'''from bs4 import BeautifulSoup
import time
from selenium import webdriver
options=webdriver.ChromeOptions()
options.add_argument('-headless')
options.add_argument('-no-sandbox')
options.add_argument('-disable-dev-shm-usage')'''

"from bs4 import BeautifulSoup\nimport time\nfrom selenium import webdriver\noptions=webdriver.ChromeOptions()\noptions.add_argument('-headless')\noptions.add_argument('-no-sandbox')\noptions.add_argument('-disable-dev-shm-usage')"

In [ ]:
'''PATH = "C:\Program Files (x86)\chromedriver.exe"'''

'PATH = "C:\\Program Files (x86)\\chromedriver.exe"'

In [ ]:
#{driver = webdriver.Chrome('chromedriver', options=options)

In [ ]:
#{driver.get("https://mc.s50.exacttarget.com/cloud/#app/Email/C12/Default.aspx?entityType=none&entityID=0&ks=ks%23Tracking")